openapi: 3.0.0
servers:
  - description: Demo deployment
    url: 'https://demo-api.windingtree.com'
  - description: Localhost
    url: 'http://localhost:3000'
info:
  description: API for reading hotels from WT
  version: 'will-be-set-at-runtime'
  title: WT reading
paths:
  /:
    get:
      summary: API info
      responses:
        '200':
          description: Basic information about this API instance.
          content:
            application/json:
              schema:
                type: object
                properties:
                  docs:
                    type: string
                    description: Link to the API documentation.
                  info:
                    type: string
                    description: Link to more information about the API.
                  version:
                    type: string
                    description: Deployed API version number.
                  config:
                    type: string
                    description: Which config is the API using. It might be useful to name configs after used ETH networks.
                  wtIndexAddress:
                    type: string
                    description: Ethereum address of used Winding Tree index.
  /hotels:
    get:
      summary: Lists hotels
      parameters:
        - name: limit
          in: query
          description: maximum number of records to return
          required: false
          schema:
            default: 30
            type: integer
            format: int32
            minimum: 0
            maximum: 300
        - name: startWith
          in: query
          description: The `id` of the first record that will be included in the result
          required: false
          schema:
            $ref: >-
              https://raw.githubusercontent.com/windingtree/wiki/4c6a5bb3ec08784099a2b3e5ad10c07a35701ff7/hotel-data-swagger.yaml#/components/schemas/EthereumAddressType
        - name: fields
          in: query
          description: >
            List of fields to return with the hotel item. Selecting only `id`
            field leads to fastest responses as all data are  trieved from
            WTIndex only.
          required: false
          schema:
            default:
              - id
              - name
              - location
            type: array
            items:
              type: string
              enum:
                - id
                - name
                - description
                - location
                - contacts
                - address
                - roomTypes
                - timezone
                - currency
                - images
                - amenities
                - managerAddress
                - updatedAt
                - cancellationPolicies
      responses:
        '200':
          description: >-
            List of hotels. The API tries to always fulfil the requested limit,
            so in some cases, the `errors` field might be present.
          content:
            application/json:
              schema:
                type: object
                properties:
                  items:
                    type: array
                    description: List of resolved hotels.
                    items:
                      $ref: '#/components/schemas/HotelListItem'
                  errors:
                    type: array
                    description: >-
                      List of checked hotels whose requested data cannot be
                      accessed (i. e. off-chain data cannot be reached).
                    items:
                      $ref: '#/components/schemas/HotelListError'
                  next:
                    description: >-
                      Uri to next page of records. When there's no next page,
                      this is not set.
                    $ref: >-
                      https://raw.githubusercontent.com/windingtree/wiki/4c6a5bb3ec08784099a2b3e5ad10c07a35701ff7/hotel-data-swagger.yaml#/components/schemas/UriType
        '400':
          $ref: '#/components/responses/InvalidRequestError'
        '500':
          $ref: '#/components/responses/InternalServerError'
  '/hotels/{hotelId}':
    get:
      summary: Get hotel `id`
      parameters:
        - name: hotelId
          required: true
          in: path
          description: Hotel Id as returned by `GET /hotel`
          schema:
            $ref: >-
              https://raw.githubusercontent.com/windingtree/wiki/4c6a5bb3ec08784099a2b3e5ad10c07a35701ff7/hotel-data-swagger.yaml#/components/schemas/EthereumAddressType
        - name: fields
          required: false
          in: query
          schema:
            type: array
            items:
              type: string
              default:
                - id
                - location
                - name
                - description
                - contacts
                - address
                - currency
                - images
                - amenities
                - updatedAt
              enum:
                - id
                - name
                - description
                - location
                - contacts
                - address
                - roomTypes
                - timezone
                - currency
                - images
                - amenities
                - managerAddress
                - updatedAt
                - cancellationPolicies
                - ratePlans
                - availability
      responses:
        '200':
          description: Hotel object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HotelDetail'
        '400':
          $ref: '#/components/responses/InvalidRequestError'
        '404':
          $ref: '#/components/responses/NotFoundError'
        '500':
          $ref: '#/components/responses/InternalServerError'
  '/hotels/{hotelId}/dataUris':
    get:
      summary: List of on-chain and off-chain identifiers where to reach all of the hotel's data.
      parameters:
        - name: hotelId
          in: path
          required: true
          description: Hotel Id as returned by `GET /hotel`
          schema:
            $ref: >-
              https://raw.githubusercontent.com/windingtree/wiki/4c6a5bb3ec08784099a2b3e5ad10c07a35701ff7/hotel-data-swagger.yaml#/components/schemas/EthereumAddressType
      responses:
        '200':
          description: Hotel data uris.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DataUrisResponse'
        '400':
          $ref: '#/components/responses/InvalidRequestError'
        '404':
          $ref: '#/components/responses/NotFoundError'
        '500':
          $ref: '#/components/responses/InternalServerError'
  '/hotels/{hotelId}/roomTypes':
    get:
      summary: List room types for hotel `id`
      parameters:
        - name: hotelId
          in: path
          required: true
          description: Hotel Id as returned by `GET /hotel`
          schema:
            $ref: >-
              https://raw.githubusercontent.com/windingtree/wiki/4c6a5bb3ec08784099a2b3e5ad10c07a35701ff7/hotel-data-swagger.yaml#/components/schemas/EthereumAddressType
        - name: fields
          in: query
          required: false
          description: Additional fields to return
          schema:
            type: string
            enum:
            - ratePlans
            - availability
      responses:
        '200':
          description: Room types list
          content:
            application/json:
              schema:
                type: object
                additionalProperties:
                  $ref: '#/components/schemas/RoomTypeResponse'
        '400':
          $ref: '#/components/responses/InvalidRequestError'
        '404':
          $ref: '#/components/responses/NotFoundError'
        '500':
          $ref: '#/components/responses/InternalServerError'
  '/hotels/{hotelId}/roomTypes/{roomTypeId}':
    get:
      summary: Get room type `id`
      parameters:
        - name: hotelId
          in: path
          required: true
          description: Hotel Id as returned by `GET /hotel`
          schema:
            $ref: >-
              https://raw.githubusercontent.com/windingtree/wiki/4c6a5bb3ec08784099a2b3e5ad10c07a35701ff7/hotel-data-swagger.yaml#/components/schemas/EthereumAddressType
        - name: roomTypeId
          in: path
          required: true
          description: Id of room type
          schema:
            $ref: >-
              https://raw.githubusercontent.com/windingtree/wiki/4c6a5bb3ec08784099a2b3e5ad10c07a35701ff7/hotel-data-swagger.yaml#/components/schemas/ObjectIdType
        - name: fields
          in: query
          required: false
          description: Additional fields to return
          schema:
            type: string
            enum:
            - ratePlans
            - availability
      responses:
        '200':
          description: Room type with id = `id`
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RoomTypeResponse'
        '400':
          $ref: '#/components/responses/InvalidRequestError'
        '404':
          $ref: '#/components/responses/NotFoundError'
        '500':
          $ref: '#/components/responses/InternalServerError'
  '/hotels/{hotelId}/roomTypes/{roomTypeId}/ratePlans':
    get:
      summary: Get rate plans of the room type `id`
      parameters:
        - name: hotelId
          in: path
          required: true
          description: Hotel Id as returned by `GET /hotel`
          schema:
            $ref: 'https://raw.githubusercontent.com/windingtree/wiki/4c6a5bb3ec08784099a2b3e5ad10c07a35701ff7/hotel-data-swagger.yaml#/components/schemas/EthereumAddressType'
        - name: roomTypeId
          in: path
          required: true
          description: Id of room type
          schema:
            $ref: 'https://raw.githubusercontent.com/windingtree/wiki/4c6a5bb3ec08784099a2b3e5ad10c07a35701ff7/hotel-data-swagger.yaml#/components/schemas/ObjectIdType'
      responses:
        '200':
          description: Rate plans for the room type
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RatePlansResponse'
        '404':
          $ref: '#/components/responses/NotFoundError'
  '/hotels/{hotelId}/roomTypes/{roomTypeId}/availability':
    get:
      summary: Get availability of the room type `id`. The availability field contains only a single key with room type id.
      parameters:
        - name: hotelId
          in: path
          required: true
          description: Hotel Id as returned by `GET /hotel`
          schema:
            $ref: 'https://raw.githubusercontent.com/windingtree/wiki/4c6a5bb3ec08784099a2b3e5ad10c07a35701ff7/hotel-data-swagger.yaml#/components/schemas/EthereumAddressType'
        - name: roomTypeId
          in: path
          required: true
          description: Id of room type
          schema:
            $ref: 'https://raw.githubusercontent.com/windingtree/wiki/4c6a5bb3ec08784099a2b3e5ad10c07a35701ff7/hotel-data-swagger.yaml#/components/schemas/ObjectIdType'
      responses:
        '200':
          description: Availability for the room type
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AvailabilityResponse'
        '404':
          $ref: '#/components/responses/NotFoundError'
  '/hotels/{hotelId}/availability':
    get:
      parameters:
        - name: hotelId
          in: path
          required: true
          description: Hotel Id as returned by `GET /hotel`
          schema:
            $ref: 'https://raw.githubusercontent.com/windingtree/wiki/4c6a5bb3ec08784099a2b3e5ad10c07a35701ff7/hotel-data-swagger.yaml#/components/schemas/EthereumAddressType'        
      responses:
        '200':
          description: Availability data for the hotel
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AvailabilityResponse'
        '404':
          $ref: '#/components/responses/NotFoundError'
  '/hotels/{hotelId}/ratePlans':
    get:
      parameters:
        - name: hotelId
          in: path
          required: true
          description: Hotel Id as returned by `GET /hotel`
          schema:
            $ref: 'https://raw.githubusercontent.com/windingtree/wiki/4c6a5bb3ec08784099a2b3e5ad10c07a35701ff7/hotel-data-swagger.yaml#/components/schemas/EthereumAddressType'        
      responses:
        '200':
          description: Rate plans for the hotel
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RatePlansResponse'
        '404':
          $ref: '#/components/responses/NotFoundError'
  '/hotels/{hotelId}/ratePlans/{ratePlanId}':
    get:
      parameters:
        - name: hotelId
          in: path
          required: true
          description: Hotel Id as returned by `GET /hotel`
          schema:
            $ref: 'https://raw.githubusercontent.com/windingtree/wiki/4c6a5bb3ec08784099a2b3e5ad10c07a35701ff7/hotel-data-swagger.yaml#/components/schemas/EthereumAddressType'        
        - name: ratePlanId
          in: path
          required: true
          description: Id of rate plan
          schema:
            $ref: 'https://raw.githubusercontent.com/windingtree/wiki/4c6a5bb3ec08784099a2b3e5ad10c07a35701ff7/hotel-data-swagger.yaml#/components/schemas/ObjectIdType'
      responses:
        '200':
          description: Rate plan details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RatePlanResponse'                
        '404':
          $ref: '#/components/responses/NotFoundError'

components:
  responses:
    InvalidRequestError:
      description: The server does not understand to the request (HTTP code 400)
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    NotFoundError:
      description: The object was not found (HTTP code 404)
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    InternalServerError:
      description: Internal server error (HTTP code 500)
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
  schemas:
    HotelListError:
      type: object
      required:
        - error
      properties:
        error:
          description: Human readable error from the API
          type: string
        originalError:
          description: Text of the original exception that caused this error
          type: string
        data:
          type: object
          description: >-
            Additional data to this error, typically contains `id` that
            identifies the errorring record.
    HotelListItem:
      allOf:
        - $ref: 'https://raw.githubusercontent.com/windingtree/wiki/4c6a5bb3ec08784099a2b3e5ad10c07a35701ff7/hotel-data-swagger.yaml#/components/schemas/HotelDescriptionBase'
        - type: object
          required:
          - id
          properties:
            id:
              $ref: 'https://raw.githubusercontent.com/windingtree/wiki/4c6a5bb3ec08784099a2b3e5ad10c07a35701ff7/hotel-data-swagger.yaml#/components/schemas/EthereumAddressType'    
            managerAddress:
              $ref: 'https://raw.githubusercontent.com/windingtree/wiki/4c6a5bb3ec08784099a2b3e5ad10c07a35701ff7/hotel-data-swagger.yaml#/components/schemas/EthereumAddressType'    
            roomTypes:
              description: Room types in the hotel
              $ref: '#/components/schemas/RoomTypesResponse'
    HotelDetail:
      allOf:
      - $ref: 'https://raw.githubusercontent.com/windingtree/wiki/4c6a5bb3ec08784099a2b3e5ad10c07a35701ff7/hotel-data-swagger.yaml#/components/schemas/HotelDescription'
      - type: object
        properties:
          ratePlans:
            $ref: 'https://raw.githubusercontent.com/windingtree/wiki/4c6a5bb3ec08784099a2b3e5ad10c07a35701ff7/hotel-data-swagger.yaml#/components/schemas/RatePlans'
          availability: 
            $ref: 'https://raw.githubusercontent.com/windingtree/wiki/4c6a5bb3ec08784099a2b3e5ad10c07a35701ff7/hotel-data-swagger.yaml#/components/schemas/AvailabilitySnapshot'
          roomTypes:
            description: Room types in the hotel
            $ref: '#/components/schemas/RoomTypesResponse'
    
    RoomTypesResponse:
      description: Mapping where keys are id of room types and the values are room types
      type: object
      additionalProperties:
        $ref: '#/components/schemas/RoomTypeResponse'
    RoomTypeResponse:
      allOf:
      - $ref: 'https://raw.githubusercontent.com/windingtree/wiki/4c6a5bb3ec08784099a2b3e5ad10c07a35701ff7/hotel-data-swagger.yaml#/components/schemas/RoomType'
      - type: object
        properties:
          id:
            $ref: 'https://raw.githubusercontent.com/windingtree/wiki/4c6a5bb3ec08784099a2b3e5ad10c07a35701ff7/hotel-data-swagger.yaml#/components/schemas/ObjectIdType'
            description: Vendor room type ID (should be unique for hotel)
          availability: 
            $ref: 'https://raw.githubusercontent.com/windingtree/wiki/4c6a5bb3ec08784099a2b3e5ad10c07a35701ff7/hotel-data-swagger.yaml#/components/schemas/AvailabilitySnapshot'
              
    RatePlansResponse:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/RatePlanResponse'
        
    RatePlanResponse:
      allOf:
        - $ref: 'https://raw.githubusercontent.com/windingtree/wiki/4c6a5bb3ec08784099a2b3e5ad10c07a35701ff7/hotel-data-swagger.yaml#/components/schemas/RatePlan'
        - type: object
          properties:
            id:
              $ref: 'https://raw.githubusercontent.com/windingtree/wiki/4c6a5bb3ec08784099a2b3e5ad10c07a35701ff7/hotel-data-swagger.yaml#/components/schemas/ObjectIdType'
              description: Vendor rate plan ID (should be unique for hotel)

    AvailabilityResponse:
      $ref: 'https://raw.githubusercontent.com/windingtree/wiki/4c6a5bb3ec08784099a2b3e5ad10c07a35701ff7/hotel-data-swagger.yaml#/components/schemas/AvailabilitySnapshot'

    DataUrisResponse:
      description: Collection of idnetifiers required to look up hotel data
      required:
        - address
        - dataUri
      allOf:
        - $ref: 'https://raw.githubusercontent.com/windingtree/wiki/4c6a5bb3ec08784099a2b3e5ad10c07a35701ff7/hotel-data-swagger.yaml#/components/schemas/HotelDataIndex'
        - type: object
          properties:
            address:
              description: Ethereum address of the hotel
              $ref: 'https://raw.githubusercontent.com/windingtree/wiki/4c6a5bb3ec08784099a2b3e5ad10c07a35701ff7/hotel-data-swagger.yaml#/components/schemas/EthereumAddressType'
            dataUri:
              description: URI of the Hotel data index (pointing off-chain)
              $ref: 'https://raw.githubusercontent.com/windingtree/wiki/4c6a5bb3ec08784099a2b3e5ad10c07a35701ff7/hotel-data-swagger.yaml#/components/schemas/UriType'

    Error:
      title: Error
      description: Default schema for errors returned by API.
      properties:
        status:
          type: number
          description: HTTP status
        code:
          type: string
          description: Computer-readable error. Use this for comparison.
        short:
          type: string
          description: Human-readable error with a short description of the error.
        long:
          type: string
          description: Verbose explanation of what happen.
